create_organ_colour <- function(){
    
    organ <-c("Bladder", "BLCA",
    "Breast","BRCA",
    "Brain",
    "Colon","COADREAD",
    "Endometrium", "UCEC",
    "Gastric",
    "Head and Neck region", "HNSC",
    "Kidney", "KIRC",
    "LARGE_INTESTINE",
    "LARGE",
    "Liver",
    "Lungs",
    "Lung",
    "Lung_NSC",
    "ESOPHAGUS",
    "OESOPHAGUS",
    "Ovary", "OV",
    "Pancreas",
    "PROSTATE",
    "Rectum",
    "STOMACH",
    "UPPER",
    "UPPER_AERODIGESTIVE",
    "URINARY",
    "Colorectal",
    "Colorectum",
    "HeadNeck",
    "HeadandNeck",
    "Testis",
    "Uterus",
    "Cervix",
    "Whitebloodcell",
    "LUAD",
    "LUSC")
    
    colours <-c("#999980","#999980",
    "#246BB2","#246BB2",
    "#d95f02",
    "#CCFFF5","#CCFFF5",
    "#3D1566","#3D1566",
    "#009E73",
    "#F0E442", "#F0E442",
    "#91cf60","#91cf60",
    "#CCFFF5",
    "#CCFFF5",
    "#D55E00",
    "#CC79A7",
    "#CC79A7",
    "#CC79A7",
    "#5C5C5C",
    "#5C5C5C",
    "#CC00CC","#CC00CC",
    "#FF9933",
    "#990033",
    "#CCFFF5",
    "#009E73",
    "#e31a1c",
    "#e31a1c",
    "#fff7bc",
    "#CCFFF5",
    "#CCFFF5",
    "#F0E442",
    "#F0E442",
    "#9ebcda",
    "#1c9099",
    "#99d8c9",
    "#beaed4",
    "#80cdc1",
    "#a6611a")
    
    org.col <- cbind(organ, colours)
    org.col <- org.col[order(org.col[,1]),]
    return(org.col)
}
